# Generated by Django 2.1.1 on 2018-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_logo',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
